site_name: Rocket
site_url: https://astrocorp.net
repo_url: https://github.com/astrocorp42/rocket

theme:
  name: 'material'

nav:
  - index.md
  - custom_script.md
  - github_releases.md
  - heroku.md

google_analytics:
  - 'UA-123569541-1'
  - 'auto'
